# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=4000, verbose_name='Site URL')),
                ('enabled', models.BooleanField(default=True, verbose_name='Site Enabled')),
            ],
            options={
                'verbose_name_plural': 'Site Configurations',
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
