# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteParsingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SiteParsingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('sites_configurations', models.ManyToManyField(to='django_crawler.SiteConfiguration')),
            ],
        ),
        migrations.AddField(
            model_name='siteparsingresult',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_crawler.SiteParsingSession'),
        ),
        migrations.AddField(
            model_name='siteparsingresult',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_crawler.SiteConfiguration'),
        ),
    ]
