# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_crawler', '0002_auto_20171228_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteparsingresult',
            name='html',
            field=models.TextField(default=b''),
        ),
    ]
